export GOPATH=${PWD}/../..
go get -u github.com/go-swagger/go-swagger/cmd/swagger
../../bin/swagger generate spec -mo ./swagger.json
if [[ $? == 0 ]]; then
    echo -e '// Code generated by swagger. DO NOT EDIT.\n// Source: swagger.json\npackage static\n\nconst SwaggerJson = `' | tee ./static/swagger_json.go
    cat ./swagger.json >> ./static/swagger_json.go
    echo -e '`\n' | tee -a ./static/swagger_json.go
fi
